spring:
  main:
    banner-mode: "off"
  application:
    name: spring-core
  threads:
    virtual:
      enabled: true

terminator:
  main:
    mission: open Pandora's box

task:
  name: "Data Processing Task"
  duration: 60
  valueList: 1, 2, 3, 4, 5
  valueSet: abc, def, ghi
  valueMap: "{key1: 100, key2: 200, key3: 300}"