spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: 300s
  flyway:
    enabled: true

terminator:
  main:
    mission: save the planet

task:
  name: "Prod Data Processing Task"
  duration: 600
  valueList: 4, 5
  valueSet: abc, def, ghi, abc # should be unique, handled by Set, but duplicates are allowed in YAML
  valueMap: "{key1: 100, key2: 200}"